src/my_www/__init__.py
from . import app

app = app.create_app()

src/my_www/app.py
import os

from flask import Flask
from flask_login import LoginManager


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = "2e4d864d-158f-480f-ba80-6e0d6e93186d"
    app.config["SQLALCHEMY_DATABASE_URI"] = os.environ["DATABASE_URI"]

    from .db import db, User

    db.init_app(app)

    from .routes import routes_blueprint

    app.register_blueprint(routes_blueprint)

    login_manager = LoginManager()
    login_manager.session_protection = None
    login_manager.login_view = "routes.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        # since the user_id is just the primary key of our user table, use it in the query for the user
        return User.query.get(int(user_id))

    db.create_all(app=app)

    return app

src/my_www/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user, login_user, logout_user

from . import db

routes_blueprint = Blueprint("routes", __name__)


@routes_blueprint.route("/login")
def login():
    return render_template("login.html")


@routes_blueprint.route("/login", methods=["POST"])
def login_form_submit():
    # login code goes here
    username = request.form.get("username")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = db.User.query.filter_by(name=username).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(
            url_for("routes.login")
        )  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user)
    return redirect(url_for("routes.index"))


@routes_blueprint.route("/signup")
def signup():
    return render_template("signup.html")


@routes_blueprint.route("/signup", methods=["POST"])
def signup_form_submit():
    # code to validate and add user to database goes here
    username = request.form.get("username")
    password = request.form.get("password")

    user = db.User.query.filter_by(
        name=username
    ).first()  # if this returns a user, then the email already exists in database

    if (
        user
    ):  # if a user is found, we want to redirect back to signup page so user can try again
        flash("Username address already exists")
        return redirect(url_for("routes.signup"))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = db.User(
        name=username,
        password=generate_password_hash(password, method="sha256"),
    )

    # add the new user to the database
    db.db.session.add(new_user)
    db.db.session.commit()
    flash("New user created, please login.")

    return redirect(url_for("routes.login"))


@routes_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("routes.index"))


@routes_blueprint.route("/")
def index():
    if current_user and current_user.is_authenticated:
        out = render_template("profile.html", user=current_user)
    else:
        # no user logged in
        out = render_template("index.html")
    return out


## Item management
@routes_blueprint.route("/items/add", methods=["POST"])
@login_required
def add_item():
    item_name = request.form.get("item_name")
    item_price = request.form.get("item_price")
    current_user.items.append(
        db.Item(name=item_name, price=int(float(item_price) * 100))
    )
    db.db.session.commit()

    return redirect(url_for("routes.index"))


@routes_blueprint.route("/items/delete/<int:id>")
@login_required
def delete_item(id):
    item = db.Item.query.filter_by(id=id).first()

    if item:
        db.db.session.delete(item)
    db.db.session.commit()
    return redirect(url_for("routes.index"))


@routes_blueprint.route("/items/summary")
@login_required
def item_summary():
    return render_template(
        "items_summary.html",
        user=current_user,
        items_total=sum(item.price for item in current_user.items),
    )

src/my_www/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shopping List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('routes.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('routes.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('routes.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('routes.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

src/my_www/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Shopping list.
</h1>
<h2 class="subtitle">
  This service allows users to manage their shopping lists.
</h2>
{% endblock %}

src/my_www/templates/items_summary.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ user.name }}!
</h1>

<div class="column is-4 is-offset-4">
    <h3 class="title">Summary</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('routes.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}

        Total cost: {{items_total / 100}}
        <br/>
        <a href="{{ url_for('routes.index') }}" class="button is-info is-fullwidth">Back to the list</a>
    </div>

</div>
{% endblock %}

src/my_www/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

src/my_www/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ user.name }}!
</h1>

<div class="column is-4 is-offset-4">
    <h3 class="title">List</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('routes.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}

        <table border="1" width="100%">
            <tr>
                <th>Item</th>
                <th>Price, £</th>
                <th>&nbsp;</th>
            </tr>
            {% for item in user.items %}
            <tr>
                <td>{{item.name}}</td>
                <td>{{'%0.2f'| format(item.price / 100)}}</td>
                <td><a href="{{ url_for('routes.delete_item', id=item.id) }}" class="button">Delete</a></td>
            </tr>
            {% endfor %}
        </table>

        <a href="{{ url_for('routes.item_summary') }}" class="button is-info is-fullwidth">Summary</a>
    </div>

    <h4>Add Item</h4>
    <div class="box">
        <form method="POST" action="{{ url_for('routes.add_item') }}">
            <div class="field">
                <div class="control">
                    <input class="input" type="text" name="item_name" placeholder="Item" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input" type="number" step="0.01" name="item_price" placeholder="Item Price">
                </div>
            </div>
            <button class="button is-block is-info is-fullwidth">Add</button>
        </form>
    </div>
</div>
{% endblock %}

src/my_www/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('routes.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}